### ISSUE TITLE
PF runtime does not allow pf execution from service principal

### ISSUE THREAD

**Issue by jakeatmsft** [Azure/llmops-gha-demo#12]
I am unable to submit job using service principal to a compute instance owned by another user.  When trying to create CI assigned to SP it doesn't recognize the SP as a valid user. 

Error in GHA:
Create run failed with FlowRequestException: Calling submit_bulk_run failed with request id: 2b6ba259-cc15-4370-9d24-3998b387735b 
Status code: 403 
Reason: Flow Runtime operation failed with Forbidden: You are not authorized to invoke this runtime as the r 
Error message: (UserError) Flow Runtime operation failed with Forbidden: You are not authorized to invoke this runtime as the runtime compute instance jacwang1 is assigned to 352ccb24-a507-464f-9f4e-d4c09a60d6c7.
Code: UserError
Message: Flow Runtime operation failed with Forbidden: You are not authorized to invoke this runtime as the runtime compute instance jacwang1 is assigned to 352ccb24-a507-464f-9f4e-d4c09a60d6c7.

**Comment by msha1026** [comment]
I faced the same issue and was able to fix it by commenting out the `runtime: <runtime-name>` line in both `run_evaluation.yml` and `run.yml`. I believe this fixes it because prompt flow will create a runtime on the fly instead. If you use an existing runtime, the Service Principal that we create in the beginning of the tutorial does not have permission to the underlying compute instance of the runtime. By allowing prompt flow to create a runtime on the fly, the Service Principal should have the correct permissions.

**Comment by jakeatmsft** [comment]
> I faced the same issue and was able to fix it by commenting out the `runtime: <runtime-name>` line in both `run_evaluation.yml` and `run.yml`. I believe this fixes it because prompt flow will create a runtime on the fly instead. If you use an existing runtime, the Service Principal that we create in the beginning of the tutorial does not have permission to the underlying compute instance of the runtime. By allowing prompt flow to create a runtime on the fly, the Service Principal should have the correct permissions.

I was also able to change runtime to "automatic", see this commit which solved the issue for me: https://github.com/jakeatmsft/llmops-gha-demo/commit/6b6fb7cce5ce7fea8f5c441e237886d1b6e0bc6b
